export const GET_ALL = "GET_ALL";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const FILTER_PRODUCT="FILTER_PRODUCT";
export const FILTER_PRODUCT_SUCCESS="FILTER_PRODUCT_SUCCESS";
